"""Notebook-facing scenario report helpers."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from html import escape
from typing import Mapping

import pandas as pd
from IPython.display import HTML, clear_output, display

from .client import SorNotebookClient
from adaptive_quantum_sor_research.scenario_catalog import load_scenarios


DEFAULT_SCENARIO_ID = "quadratic-pair-override"
DEFAULT_RESET_MODE = "PURGE_AND_REPOPULATE"
DEFAULT_ORDER_REF = "scenario-report-order"

REPORT_CSS = """
<style>
:root {
  --sor-ink: #111827;
  --sor-muted: #5b6472;
  --sor-line: #d7dde6;
  --sor-panel: #f8fafc;
  --sor-panel-2: #eef5ff;
  --sor-blue: #1d4ed8;
  --sor-green: #047857;
  --sor-amber: #b45309;
  --sor-red: #b91c1c;
}
.sor-report {font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; color: var(--sor-ink);}
.sor-hero {border: 1px solid var(--sor-line); border-radius: 8px; padding: 18px 20px; margin: 4px 0 18px 0; background: linear-gradient(180deg, #ffffff 0%, #f8fafc 100%);}
.sor-hero h1 {font-size: 24px; margin: 0 0 6px 0; letter-spacing: 0;}
.sor-hero p {margin: 0; color: var(--sor-muted); font-size: 14px;}
.sor-section {margin: 22px 0 10px 0;}
.sor-section h2 {font-size: 18px; margin: 0 0 4px 0; letter-spacing: 0;}
.sor-section p {margin: 0 0 8px 0; color: var(--sor-muted); font-size: 13px;}
.sor-kpi-grid {display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 10px; margin: 10px 0 18px 0;}
.sor-kpi {border: 1px solid var(--sor-line); border-radius: 8px; padding: 12px 14px; background: #ffffff;}
.sor-kpi-label {font-size: 12px; color: var(--sor-muted); margin-bottom: 5px;}
.sor-kpi-value {font-size: 20px; font-weight: 700; line-height: 1.15;}
.sor-badge {display: inline-block; border-radius: 999px; padding: 3px 9px; font-size: 12px; font-weight: 700;}
.sor-pass {background: #ecfdf5; color: var(--sor-green); border: 1px solid #a7f3d0;}
.sor-warn {background: #fffbeb; color: var(--sor-amber); border: 1px solid #fde68a;}
.sor-fail {background: #fef2f2; color: var(--sor-red); border: 1px solid #fecaca;}
.sor-note {border-left: 4px solid var(--sor-blue); background: var(--sor-panel-2); padding: 10px 12px; margin: 10px 0 18px 0; color: #1e3a8a;}
table.sor-report-table {border-collapse: collapse; width: 100%; table-layout: auto; margin: 8px 0 18px 0; font-size: 13px;}
table.sor-report-table th, table.sor-report-table td {border: 1px solid var(--sor-line); padding: 7px 9px; vertical-align: top; white-space: normal; overflow-wrap: anywhere; word-break: break-word; max-width: 560px; text-align: left;}
table.sor-report-table th {background: var(--sor-panel); color: var(--sor-ink); font-weight: 700;}
table.sor-report-table tbody tr:nth-child(even) {background: #fcfdff;}
</style>
"""


@dataclass(frozen=True)
class ScenarioRunInputs:
    """Scenario run controls read from widgets or defaults."""

    scenario_id: str
    seed: int
    ticks: int
    reset_mode: str
    max_route_attempts: int
    route_timeout_millis: int
    parent_orders: list[dict[str, object]]


@dataclass(frozen=True)
class ScenarioReportResult:
    """Frames and raw payloads generated by one scenario report run."""

    inputs: ScenarioRunInputs
    reset: dict
    run: dict
    summary: pd.DataFrame
    events: pd.DataFrame
    parent_order_results: pd.DataFrame
    fills: pd.DataFrame
    manifest: pd.DataFrame
    result_list: pd.DataFrame


class ScenarioReportApp:
    """Small controller that keeps scenario_runner.ipynb readable."""

    def __init__(
        self,
        client: SorNotebookClient | None = None,
        *,
        default_scenario_id: str = DEFAULT_SCENARIO_ID,
    ) -> None:
        pd.set_option("display.max_colwidth", None)
        pd.set_option("display.max_columns", None)
        pd.set_option("display.width", 0)
        self.client = client or SorNotebookClient()
        self.scenarios = load_scenarios()
        self.scenario_lookup = {scenario.scenario_id: scenario for scenario in self.scenarios}
        self.default_scenario_id = self._default_scenario_id(default_scenario_id)
        default_scenario = self.scenario_lookup[self.default_scenario_id]
        self.defaults = ScenarioRunInputs(
            scenario_id=self.default_scenario_id,
            seed=int(default_scenario.seed),
            ticks=int(default_scenario.ticks),
            reset_mode=DEFAULT_RESET_MODE,
            max_route_attempts=8,
            route_timeout_millis=1000,
            parent_orders=build_parent_orders(
                2,
                instrument_id=0,
                side="BUY",
                quantity=7000,
                urgency_id=1,
                at_tick=1,
                submit_mode="SIMULATED",
                client_order_ref=DEFAULT_ORDER_REF,
            ),
        )
        self.widget_controls: dict[str, object] = {}
        self.preview_output = None
        self.report_output = None
        self.widgets = _load_widgets()

    def display_controls(self) -> None:
        """Render the widget control panel, falling back to defaults if needed."""

        display_styles()
        if self.widgets is None:
            display_note(
                "ipywidgets is not installed. Install tools/python-research/requirements.txt to enable dropdown controls; "
                "the notebook will use the Python defaults."
            )
            return

        widgets = self.widgets
        scenario_options = [(f"{scenario.scenario_id} ({scenario.category})", scenario.scenario_id) for scenario in self.scenarios]
        self.widget_controls = {
            "scenario_id": widgets.Dropdown(options=scenario_options, value=self.defaults.scenario_id, description="Scenario", layout=widgets.Layout(width="520px")),
            "seed": widgets.IntText(value=self.defaults.seed, description="Seed"),
            "ticks": widgets.IntSlider(value=self.defaults.ticks, min=1, max=120, step=1, description="Ticks", continuous_update=False),
            "reset_mode": widgets.Dropdown(options=["PURGE_AND_REPOPULATE", "KEEP_POLICY_PURGE_STATS", "ISOLATED", "APPEND"], value=self.defaults.reset_mode, description="Reset"),
            "max_route_attempts": widgets.IntSlider(value=self.defaults.max_route_attempts, min=1, max=32, step=1, description="Attempts", continuous_update=False),
            "route_timeout_millis": widgets.IntSlider(value=self.defaults.route_timeout_millis, min=100, max=10000, step=100, description="Timeout ms", continuous_update=False),
            "parent_order_count": widgets.IntSlider(value=len(self.defaults.parent_orders), min=1, max=5, step=1, description="Orders", continuous_update=False),
            "instrument_id": widgets.IntSlider(value=0, min=0, max=1, step=1, description="Instrument", continuous_update=False),
            "side": widgets.Dropdown(options=["BUY", "SELL"], value="BUY", description="Side"),
            "quantity": widgets.IntText(value=7000, description="Quantity"),
            "urgency_id": widgets.Dropdown(options=[("LOW", 0), ("NORMAL", 1), ("HIGH", 2)], value=1, description="Urgency"),
            "at_tick": widgets.IntSlider(value=1, min=0, max=max(1, self.defaults.ticks - 1), step=1, description="At tick", continuous_update=False),
            "submit_mode": widgets.Dropdown(options=["SIMULATED", "API"], value="SIMULATED", description="Submit"),
            "client_order_ref": widgets.Text(value=DEFAULT_ORDER_REF, description="Ref", layout=widgets.Layout(width="360px")),
        }
        self.widget_controls["scenario_id"].observe(self._sync_scenario_defaults, names="value")
        self.widget_controls["ticks"].observe(self._sync_tick_bounds, names="value")
        update_button = widgets.Button(
            description="Update setup",
            button_style="primary",
            tooltip="Refresh the setup preview from the current widget values.",
        )
        report_button = widgets.Button(
            description="Execute",
            button_style="success",
            tooltip="Run the scenario with the current setup and display the report.",
        )
        self.preview_output = widgets.Output()
        self.report_output = widgets.Output()

        def _refresh_preview(_button) -> None:
            self.display_planned_run()

        def _display_report(_button) -> None:
            self.run_and_display()

        update_button.on_click(_refresh_preview)
        report_button.on_click(_display_report)

        display(HTML("<div class='sor-report sor-section'><h2>Widget Control Panel</h2><p>Choose the run setup here, then run the execution cell to generate the report.</p></div>"))
        display(widgets.VBox([
            widgets.HBox([self.widget_controls["scenario_id"], self.widget_controls["reset_mode"]]),
            widgets.HBox([self.widget_controls["seed"], self.widget_controls["ticks"], self.widget_controls["max_route_attempts"], self.widget_controls["route_timeout_millis"]]),
            widgets.HBox([self.widget_controls["parent_order_count"], self.widget_controls["instrument_id"], self.widget_controls["side"], self.widget_controls["urgency_id"]]),
            widgets.HBox([self.widget_controls["quantity"], self.widget_controls["at_tick"], self.widget_controls["submit_mode"], self.widget_controls["client_order_ref"]]),
            widgets.HBox([update_button, report_button]),
            self.preview_output,
            self.report_output,
        ]))

    def display_planned_run(self) -> None:
        """Render the manifest and parent orders before any API call is made."""

        if self.preview_output is not None:
            with self.preview_output:
                clear_output(wait=True)
                self._render_planned_run()
            return
        self._render_planned_run()

    def _render_planned_run(self) -> None:
        """Render the setup preview into the current display target."""

        inputs = self.read_inputs()
        display_styles()
        display_header(
            "Scenario Execution Report - Planned Run",
            "Configuration preview before any API call is made.",
            datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S"),
        )
        display_table("Run Manifest", manifest_frame(inputs), "These are the scenario controls that will be sent to the SOR API.")
        display_table("Parent Orders To Submit", planned_orders_frame(inputs), "Each row is one parent order that will be routed during the scenario run.")

    def run_and_display(self) -> ScenarioReportResult:
        """Execute reset and run calls, then render the user-friendly report."""

        if self.report_output is not None:
            with self.report_output:
                clear_output(wait=True)
                result = self.run()
                display_report(result)
            return result
        result = self.run()
        display_report(result)
        return result

    def run(self) -> ScenarioReportResult:
        """Execute the configured scenario and return raw payloads plus frames."""

        inputs = self.read_inputs()
        started_at = datetime.now(timezone.utc)
        reset = self.client.reset_scenario(inputs.scenario_id, seed=inputs.seed, ticks=inputs.ticks, reset_mode=inputs.reset_mode)
        run = self.client.run_scenario(
            inputs.scenario_id,
            seed=inputs.seed,
            ticks=inputs.ticks,
            reset_mode=inputs.reset_mode,
            parent_orders=inputs.parent_orders,
            max_route_attempts=inputs.max_route_attempts,
            route_timeout_millis=inputs.route_timeout_millis,
            simulator_generated_orders=False,
        )
        summary = self.client.scenario_summary_dataframe()
        events = self.client.scenario_events_dataframe()
        completed_at = datetime.now(timezone.utc)

        parent_order_results = parent_order_results_frame(run)
        fills = fills_frame(run)
        manifest = manifest_frame(inputs, started_at=started_at, completed_at=completed_at)
        result_list = result_list_frame(inputs, run, parent_order_results, fills)
        return ScenarioReportResult(
            inputs=inputs,
            reset=reset,
            run=run,
            summary=summary,
            events=events,
            parent_order_results=parent_order_results,
            fills=fills,
            manifest=manifest,
            result_list=result_list,
        )

    def read_inputs(self) -> ScenarioRunInputs:
        """Read current widget values or return deterministic defaults."""

        if not self.widget_controls:
            return self.defaults
        selected_scenario_id = self.widget_controls["scenario_id"].value
        selected_ticks = int(self.widget_controls["ticks"].value)
        return ScenarioRunInputs(
            scenario_id=selected_scenario_id,
            seed=int(self.widget_controls["seed"].value),
            ticks=selected_ticks,
            reset_mode=self.widget_controls["reset_mode"].value,
            max_route_attempts=int(self.widget_controls["max_route_attempts"].value),
            route_timeout_millis=int(self.widget_controls["route_timeout_millis"].value),
            parent_orders=build_parent_orders(
                self.widget_controls["parent_order_count"].value,
                self.widget_controls["instrument_id"].value,
                self.widget_controls["side"].value,
                self.widget_controls["quantity"].value,
                self.widget_controls["urgency_id"].value,
                min(self.widget_controls["at_tick"].value, selected_ticks - 1),
                self.widget_controls["submit_mode"].value,
                self.widget_controls["client_order_ref"].value,
            ),
        )

    def _default_scenario_id(self, scenario_id: str) -> str:
        if scenario_id in self.scenario_lookup:
            return scenario_id
        return next(iter(self.scenario_lookup.values())).scenario_id

    def _sync_scenario_defaults(self, change: Mapping[str, object]) -> None:
        scenario = self.scenario_lookup[change["new"]]
        self.widget_controls["seed"].value = int(scenario.seed)
        self.widget_controls["ticks"].value = int(scenario.ticks)
        self.widget_controls["at_tick"].max = max(0, int(scenario.ticks) - 1)

    def _sync_tick_bounds(self, change: Mapping[str, object]) -> None:
        self.widget_controls["at_tick"].max = max(0, int(change["new"]) - 1)


def build_parent_orders(
    count: int,
    instrument_id: int,
    side: str,
    quantity: int,
    urgency_id: int,
    at_tick: int,
    submit_mode: str,
    client_order_ref: str,
) -> list[dict[str, object]]:
    """Build parent order rows from compact widget inputs."""

    rows: list[dict[str, object]] = []
    for index in range(int(count)):
        rows.append({
            "instrumentId": int(instrument_id),
            "side": side,
            "quantity": int(quantity),
            "urgencyId": int(urgency_id),
            "atTick": int(at_tick) + index,
            "submitMode": submit_mode,
            "clientOrderRef": f"{client_order_ref}-{index + 1}",
        })
    return rows


def display_report(result: ScenarioReportResult) -> None:
    """Render all report sections from a completed scenario run."""

    metrics = report_metrics(result.inputs, result.run, result.parent_order_results, result.fills)
    summary_frame = result.summary.add_prefix("summary.")
    reset_frame = pd.DataFrame([result.reset]).add_prefix("reset.")
    run_frame = pd.DataFrame([result.run]).drop(columns=["parentOrderResults"], errors="ignore").add_prefix("run.")

    display_styles()
    display_header(
        "Scenario Execution Report - Results",
        f"{result.inputs.scenario_id} | seed {result.inputs.seed} | reset {result.inputs.reset_mode}",
        metrics["completedAtUtc"],
    )
    display(HTML(f"<div class='sor-report'>{badge(metrics['outcomeLabel'], metrics['outcomeTone'])}</div>"))
    display_kpis([
        ("Run outcome", metrics["outcomeLabel"]),
        ("Replay safe", format_bool(metrics["replaySafe"])),
        ("Filled qty", metrics["totalFilled"]),
        ("Remaining qty", metrics["totalRemaining"]),
        ("Child orders", metrics["childOrderCount"]),
        ("Venues used", metrics["venueCount"]),
    ])
    display_note(metrics["whatHappened"])

    display_table("1. Run Manifest", result.manifest, "Exactly what was run and when.")
    display_table("2. Result List", result.result_list, "Plain-language checklist of the important results.")
    order_columns = [
        "scenarioId", "parentOrderId", "clientOrderRef", "atTick", "submitMode",
        "filledQty", "remainingQty", "statusName", "childOrderCount", "routeAttempts", "timedOut",
    ]
    display_table(
        "3. Parent Order Results",
        select_columns(result.parent_order_results, order_columns),
        "One row per submitted parent order.",
    )
    fill_columns = [
        "clientOrderRef", "routeAttempt", "instrumentSymbol", "venueId", "venueName",
        "sideName", "childQty", "filledQty", "priceTicks", "notionalTicks", "policyVersion", "policyHash64",
    ]
    display_table(
        "4. Venue Fill Breakdown",
        select_columns(result.fills, fill_columns),
        "Venue-level evidence for child orders and fills.",
    )
    display_table("5. Scenario Summary", summary_frame, "Deterministic replay summary returned by the scenario service.")
    display_table("6. Reset Evidence", reset_frame, "What the reset did before the scenario run.")
    display_table("7. Run Response Evidence", run_frame, "Top-level run response excluding nested parent order details shown above.")
    event_columns = ["sequence", "eventId", "timestampNanos", "event", "componentId", "eventType", "correlationId", "message"]
    display_table(
        "8. Lifecycle Event Log",
        select_columns(result.events, event_columns),
        "Control-plane and lifecycle events captured during the run.",
    )


def parent_order_results_frame(run: Mapping[str, object]) -> pd.DataFrame:
    """Flatten parent order results from the scenario API response."""

    frame = pd.DataFrame([
        {key: value for key, value in result.items() if key != "fills"}
        for result in run.get("parentOrderResults", [])
    ])
    if not frame.empty and "status" in frame.columns:
        frame["statusName"] = frame["status"].map(status_name)
    return frame


def fills_frame(run: Mapping[str, object]) -> pd.DataFrame:
    """Flatten nested child fill rows from the scenario API response."""

    fill_rows: list[dict[str, object]] = []
    for result in run.get("parentOrderResults", []):
        for fill in result.get("fills", []):
            row = dict(fill)
            row["clientOrderRef"] = result.get("clientOrderRef", "")
            fill_rows.append(row)
    return pd.DataFrame(fill_rows)


def manifest_frame(
    inputs: ScenarioRunInputs,
    *,
    started_at: datetime | None = None,
    completed_at: datetime | None = None,
) -> pd.DataFrame:
    """Build the run manifest frame shown in preview and result reports."""

    row: dict[str, object] = {
        "scenarioId": inputs.scenario_id,
        "seed": inputs.seed,
        "ticks": inputs.ticks,
        "resetMode": inputs.reset_mode,
        "maxRouteAttempts": inputs.max_route_attempts,
        "routeTimeoutMillis": inputs.route_timeout_millis,
        "parentOrderCount": len(inputs.parent_orders),
    }
    if started_at is not None:
        row["startedAtUtc"] = started_at.strftime("%Y-%m-%d %H:%M:%S")
    if completed_at is not None:
        row["completedAtUtc"] = completed_at.strftime("%Y-%m-%d %H:%M:%S")
    return frame_from_rows([row])


def planned_orders_frame(inputs: ScenarioRunInputs) -> pd.DataFrame:
    """Build the parent-order preview frame."""

    return frame_from_rows(inputs.parent_orders, [
        "clientOrderRef", "instrumentId", "side", "quantity", "urgencyId", "atTick", "submitMode",
    ])


def result_list_frame(
    inputs: ScenarioRunInputs,
    run: Mapping[str, object],
    parent_order_results: pd.DataFrame,
    fills: pd.DataFrame,
) -> pd.DataFrame:
    """Build the plain-language checklist for a completed scenario run."""

    metrics = report_metrics(inputs, run, parent_order_results, fills)
    return pd.DataFrame([
        {"Check": "Run accepted by API", "Result": format_bool(metrics["runSuccess"]), "Meaning": run.get("message", "")},
        {"Check": "Replay-safe reset mode", "Result": format_bool(metrics["replaySafe"]), "Meaning": "Clean replay evidence" if metrics["replaySafe"] else "Append or non-replay-safe mode used"},
        {"Check": "Parent orders submitted", "Result": metrics["orderCount"], "Meaning": "Configured parent order count"},
        {"Check": "Parent orders fully filled", "Result": metrics["completedOrders"], "Meaning": "Orders with zero remaining quantity"},
        {"Check": "Timed out orders", "Result": metrics["timedOutOrders"], "Meaning": "Should be zero for a clean run"},
        {"Check": "Total filled quantity", "Result": metrics["totalFilled"], "Meaning": "Aggregate filled quantity across parent orders"},
        {"Check": "Total remaining quantity", "Result": metrics["totalRemaining"], "Meaning": "Residual quantity left after routing"},
        {"Check": "Venues used", "Result": metrics["venueCount"], "Meaning": "Distinct venues in child fill evidence"},
    ])


def report_metrics(
    inputs: ScenarioRunInputs,
    run: Mapping[str, object],
    parent_order_results: pd.DataFrame,
    fills: pd.DataFrame,
) -> dict[str, object]:
    """Compute KPI values and the report summary sentence."""

    order_count = len(inputs.parent_orders)
    completed_orders = 0 if parent_order_results.empty or "remainingQty" not in parent_order_results.columns else int((pd.to_numeric(parent_order_results["remainingQty"], errors="coerce").fillna(0) == 0).sum())
    timed_out_orders = 0 if parent_order_results.empty or "timedOut" not in parent_order_results.columns else int(parent_order_results["timedOut"].astype(bool).sum())
    total_filled = numeric_sum(parent_order_results, "filledQty")
    total_remaining = numeric_sum(parent_order_results, "remainingQty")
    child_order_count = numeric_sum(parent_order_results, "childOrderCount")
    route_attempts = numeric_sum(parent_order_results, "routeAttempts")
    venue_count = 0 if fills.empty or "venueId" not in fills.columns else int(fills["venueId"].nunique())
    run_success = bool(run.get("success", False))
    replay_safe = bool(run.get("replaySafe", False))
    needs_review = (not run_success) or (not replay_safe) or timed_out_orders > 0 or total_remaining > 0
    outcome_label = "Completed" if not needs_review else "Needs review"
    what_happened = (
        f"The notebook reset scenario '{inputs.scenario_id}' with seed {inputs.seed} and ran {inputs.ticks} ticks using {inputs.reset_mode}. "
        f"It submitted {order_count} parent order(s), produced {child_order_count} child order(s) over {route_attempts} route attempt(s), "
        f"filled {total_filled} units, and left {total_remaining} units remaining. "
        f"The run status is {outcome_label.lower()}."
    )
    return {
        "orderCount": order_count,
        "completedOrders": completed_orders,
        "timedOutOrders": timed_out_orders,
        "totalFilled": total_filled,
        "totalRemaining": total_remaining,
        "childOrderCount": child_order_count,
        "routeAttempts": route_attempts,
        "venueCount": venue_count,
        "runSuccess": run_success,
        "replaySafe": replay_safe,
        "outcomeLabel": outcome_label,
        "outcomeTone": "pass" if not needs_review else "warn",
        "whatHappened": what_happened,
        "completedAtUtc": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S"),
    }


def display_styles() -> None:
    display(HTML(REPORT_CSS))


def display_header(title: str, subtitle: str, generated_at: str) -> None:
    display(HTML(f"""
    <div class="sor-report sor-hero">
      <h1>{escape(title)}</h1>
      <p>{escape(subtitle)}</p>
      <p>Generated at {escape(generated_at)} UTC</p>
    </div>
    """))


def display_section(title: str, subtitle: str = "") -> None:
    subtitle_html = f"<p>{escape(subtitle)}</p>" if subtitle else ""
    display(HTML(f"<div class='sor-report sor-section'><h2>{escape(title)}</h2>{subtitle_html}</div>"))


def display_note(text: str) -> None:
    display(HTML(f"<div class='sor-report sor-note'>{escape(text)}</div>"))


def display_table(title: str, frame: pd.DataFrame | None, subtitle: str = "") -> None:
    display_section(title, subtitle)
    if frame is None or frame.empty:
        display_note("No rows were returned for this section.")
        return
    html = frame.to_html(index=False, escape=True)
    html = html.replace('class="dataframe"', 'class="sor-report-table"')
    display(HTML("<div class='sor-report'>" + html + "</div>"))


def display_kpis(cards: list[tuple[str, object]]) -> None:
    html_cards = []
    for label, value in cards:
        html_cards.append(
            "<div class='sor-kpi'>"
            f"<div class='sor-kpi-label'>{escape(str(label))}</div>"
            f"<div class='sor-kpi-value'>{escape(str(value))}</div>"
            "</div>"
        )
    display(HTML("<div class='sor-report sor-kpi-grid'>" + "".join(html_cards) + "</div>"))


def badge(label: str, tone: str) -> str:
    css = {"pass": "sor-pass", "warn": "sor-warn", "fail": "sor-fail"}.get(tone, "sor-warn")
    return f"<span class='sor-badge {css}'>{escape(str(label))}</span>"


def frame_from_rows(rows: list[Mapping[str, object]], columns: list[str] | None = None) -> pd.DataFrame:
    frame = pd.DataFrame(rows)
    if columns:
        for column in columns:
            if column not in frame.columns:
                frame[column] = ""
        frame = frame[columns]
    return frame


def select_columns(frame: pd.DataFrame, columns: list[str]) -> pd.DataFrame:
    if frame is None or frame.empty:
        return frame
    return frame[[column for column in columns if column in frame.columns]]


def numeric_sum(frame: pd.DataFrame, column: str) -> int:
    if frame is None or frame.empty or column not in frame.columns:
        return 0
    return int(pd.to_numeric(frame[column], errors="coerce").fillna(0).sum())


def format_bool(value: object) -> str:
    return "Yes" if bool(value) else "No"


def status_name(status: object) -> str:
    mapping = {0: "NEW", 1: "ACKED", 2: "PARTIALLY_FILLED", 3: "FILLED", 4: "REJECTED", 5: "CANCELLED"}
    try:
        return mapping.get(int(status), str(status))
    except (TypeError, ValueError):
        return str(status)


def _load_widgets():
    try:
        import ipywidgets as widgets
    except ModuleNotFoundError:
        return None
    return widgets
