"""
Purpose: Builds notebook order-submission reports from HTTP API responses.
Usage: Use it from notebooks to submit sample orders and display typed response tables.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from html import escape

import pandas as pd
from IPython.display import HTML, clear_output, display

from .notebook_client import SorNotebookClient


DEFAULT_BASE_URL = "http://127.0.0.1:8080"
DEFAULT_TIMEOUT_SECONDS = 5.0

REPORT_CSS = """
<style>
:root {
  --sor-ink: #111827;
  --sor-muted: #5b6472;
  --sor-line: #d7dde6;
  --sor-panel: #f8fafc;
  --sor-panel-2: #eef5ff;
  --sor-blue: #1d4ed8;
  --sor-green: #047857;
  --sor-amber: #b45309;
  --sor-red: #b91c1c;
}
.sor-report {font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; color: var(--sor-ink);}
.sor-hero {border: 1px solid var(--sor-line); border-radius: 8px; padding: 18px 20px; margin: 4px 0 18px 0; background: linear-gradient(180deg, #ffffff 0%, #f8fafc 100%);}
.sor-hero h1 {font-size: 24px; margin: 0 0 6px 0; letter-spacing: 0;}
.sor-hero p {margin: 0; color: var(--sor-muted); font-size: 14px;}
.sor-section {margin: 22px 0 10px 0;}
.sor-section h2 {font-size: 18px; margin: 0 0 4px 0; letter-spacing: 0;}
.sor-section p {margin: 0 0 8px 0; color: var(--sor-muted); font-size: 13px;}
.sor-kpi-grid {display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 10px; margin: 10px 0 18px 0;}
.sor-kpi {border: 1px solid var(--sor-line); border-radius: 8px; padding: 12px 14px; background: #ffffff;}
.sor-kpi-label {font-size: 12px; color: var(--sor-muted); margin-bottom: 5px;}
.sor-kpi-value {font-size: 22px; font-weight: 700; line-height: 1.15;}
.sor-badge {display: inline-block; border-radius: 999px; padding: 3px 9px; font-size: 12px; font-weight: 700;}
.sor-pass {background: #ecfdf5; color: var(--sor-green); border: 1px solid #a7f3d0;}
.sor-warn {background: #fffbeb; color: var(--sor-amber); border: 1px solid #fde68a;}
.sor-fail {background: #fef2f2; color: var(--sor-red); border: 1px solid #fecaca;}
.sor-note {border-left: 4px solid var(--sor-blue); background: var(--sor-panel-2); padding: 10px 12px; margin: 10px 0 18px 0; color: #1e3a8a;}
.sor-error {border-left-color: var(--sor-red); background: #fef2f2; color: #7f1d1d;}
table.sor-report-table {border-collapse: collapse; width: 100%; table-layout: auto; margin: 8px 0 18px 0; font-size: 13px;}
table.sor-report-table th, table.sor-report-table td {border: 1px solid var(--sor-line); padding: 7px 9px; vertical-align: top; white-space: normal; overflow-wrap: anywhere; word-break: break-word; max-width: 560px; text-align: left;}
table.sor-report-table th {background: var(--sor-panel); color: var(--sor-ink); font-weight: 700;}
table.sor-report-table tbody tr:nth-child(even) {background: #fcfdff;}
</style>
"""


@dataclass(frozen=True)
class SubmitOrderInputs:
    """Parent order controls read from widgets or defaults."""

    base_url: str = DEFAULT_BASE_URL
    timeout_seconds: float = DEFAULT_TIMEOUT_SECONDS
    instrument_id: int = 0
    side: int = 1
    quantity: int = 1000
    urgency_id: int = 1

    def payload(self) -> dict[str, int]:
        return {
            "instrumentId": int(self.instrument_id),
            "side": int(self.side),
            "quantity": int(self.quantity),
            "urgencyId": int(self.urgency_id),
        }


@dataclass(frozen=True)
class SubmitOrderReportResult:
    """Raw payloads and frames generated by one submit-order report."""

    inputs: SubmitOrderInputs
    order: dict
    status: dict
    manifest: pd.DataFrame
    payload_frame: pd.DataFrame
    order_frame: pd.DataFrame
    status_frame: pd.DataFrame
    children_frame: pd.DataFrame
    result_list: pd.DataFrame


class SubmitParentOrderApp:
    """Small controller that keeps submit_parent_order.ipynb readable."""

    def __init__(self, defaults: SubmitOrderInputs | None = None) -> None:
        pd.set_option("display.max_colwidth", None)
        pd.set_option("display.max_columns", None)
        pd.set_option("display.width", 0)
        self.defaults = defaults or SubmitOrderInputs()
        self.widget_controls: dict[str, object] = {}
        self.status_output = None
        self.report_output = None
        self.widgets = _load_widgets()

    def display_controls(self) -> None:
        """Render the widget control panel, falling back to defaults if needed."""

        display_styles()
        if self.widgets is None:
            display_note(
                "ipywidgets is not installed. Install tools/python-research/requirements.txt to enable friendly controls; "
                "the notebook will use the Python defaults."
            )
            return

        widgets = self.widgets
        self.widget_controls = {
            "base_url": widgets.Text(value=self.defaults.base_url, description="API URL", layout=widgets.Layout(width="420px")),
            "timeout_seconds": widgets.FloatSlider(value=self.defaults.timeout_seconds, min=1.0, max=30.0, step=0.5, description="Timeout", continuous_update=False),
            "instrument_id": widgets.IntSlider(value=self.defaults.instrument_id, min=0, max=1, step=1, description="Instrument", continuous_update=False),
            "side": widgets.Dropdown(options=[("BUY", 1), ("SELL", 2)], value=self.defaults.side, description="Side"),
            "quantity": widgets.IntText(value=self.defaults.quantity, description="Quantity"),
            "urgency_id": widgets.Dropdown(options=[("LOW", 0), ("NORMAL", 1), ("HIGH", 2)], value=self.defaults.urgency_id, description="Urgency"),
        }
        submit_button = widgets.Button(
            description="Submit order",
            button_style="success",
            tooltip="Submit the parent order and render the report.",
        )
        reset_button = widgets.Button(description="Clear", button_style="warning", tooltip="Clear the submit report output.")
        self.status_output = widgets.Output()
        self.report_output = widgets.Output()
        submit_button.on_click(lambda _button: self.submit_and_display())
        reset_button.on_click(lambda _button: self.clear_report())

        display(HTML("<div class='sor-report sor-section'><h2>Widget Control Panel</h2><p>Choose the parent order payload, then click Submit order or run the next cell.</p></div>"))
        display(widgets.VBox([
            widgets.HBox([self.widget_controls["base_url"], self.widget_controls["timeout_seconds"]]),
            widgets.HBox([self.widget_controls["instrument_id"], self.widget_controls["side"], self.widget_controls["quantity"], self.widget_controls["urgency_id"]]),
            widgets.HBox([submit_button, reset_button]),
            self.status_output,
            self.report_output,
        ]))

    def clear_report(self) -> None:
        """Clear the widget-backed report output."""

        if self.report_output is not None:
            with self.report_output:
                clear_output(wait=True)
        self._set_status("Submit report cleared.")

    def read_inputs(self) -> SubmitOrderInputs:
        """Read current widget values."""

        if not self.widget_controls:
            return self.defaults
        return SubmitOrderInputs(
            base_url=str(self.widget_controls["base_url"].value),
            timeout_seconds=float(self.widget_controls["timeout_seconds"].value),
            instrument_id=int(self.widget_controls["instrument_id"].value),
            side=int(self.widget_controls["side"].value),
            quantity=int(self.widget_controls["quantity"].value),
            urgency_id=int(self.widget_controls["urgency_id"].value),
        )

    def submit_and_display(self) -> SubmitOrderReportResult | None:
        """Submit the configured parent order and render the report."""

        self._set_status("Submitting parent order...")
        if self.report_output is not None:
            with self.report_output:
                clear_output(wait=True)
                result = self._submit_and_render()
            self._set_status("Submit failed. See report below." if result is None else "Submit report updated.")
            return result
        return self._submit_and_render()

    def _submit_and_render(self) -> SubmitOrderReportResult | None:
        inputs = self.read_inputs()
        try:
            result = submit_order(inputs)
        except Exception as exc:
            display_failure_report(inputs, exc)
            return None
        display_report(result)
        return result

    def _set_status(self, message: str) -> None:
        if self.status_output is None:
            return
        with self.status_output:
            clear_output(wait=True)
            display_note(message)


def submit_order(inputs: SubmitOrderInputs) -> SubmitOrderReportResult:
    """Submit one parent order and return raw payloads plus report frames."""

    submitted_at = datetime.now(timezone.utc)
    payload = inputs.payload()
    client = SorNotebookClient(inputs.base_url, timeout_seconds=inputs.timeout_seconds)
    order = client.submit_order(payload)
    status = client.order_status(order["parentOrderId"])
    completed_at = datetime.now(timezone.utc)

    child_orders = status.get("childOrders", []) or []
    filled_qty = int(status.get("filledQty", 0))
    remaining_qty = int(status.get("remainingQty", payload.get("quantity", 0)))
    manifest = pd.DataFrame([{
        "baseUrl": inputs.base_url,
        "submittedAtUtc": submitted_at.strftime("%Y-%m-%d %H:%M:%S"),
        "completedAtUtc": completed_at.strftime("%Y-%m-%d %H:%M:%S"),
        "timeoutSeconds": inputs.timeout_seconds,
    }])
    return SubmitOrderReportResult(
        inputs=inputs,
        order=order,
        status=status,
        manifest=manifest,
        payload_frame=pd.DataFrame([payload]),
        order_frame=pd.DataFrame([order]).add_prefix("submit."),
        status_frame=pd.DataFrame([{key: value for key, value in status.items() if key != "childOrders"}]).add_prefix("status."),
        children_frame=pd.DataFrame(child_orders),
        result_list=pd.DataFrame([
            {"Check": "Order submitted", "Result": "Yes", "Meaning": f"parentOrderId={order.get('parentOrderId')}"},
            {"Check": "Requested quantity", "Result": payload.get("quantity"), "Meaning": "Quantity sent to /orders"},
            {"Check": "Filled quantity", "Result": filled_qty, "Meaning": "Quantity routed/filled by the engine"},
            {"Check": "Remaining quantity", "Result": remaining_qty, "Meaning": "Residual quantity after routing"},
            {"Check": "Child orders", "Result": len(child_orders), "Meaning": "Venue-level child order count"},
        ]),
    )


def display_report(result: SubmitOrderReportResult) -> None:
    """Render a professional parent-order submission report."""

    display_styles()
    payload = result.inputs.payload()
    filled_qty = int(result.status.get("filledQty", 0))
    remaining_qty = int(result.status.get("remainingQty", payload.get("quantity", 0)))
    child_orders = result.status.get("childOrders", []) or []
    outcome = "Completed" if remaining_qty == 0 else "Accepted with residual"
    tone = "pass" if remaining_qty == 0 else "warn"
    completed_at = first_value(result.manifest, "completedAtUtc", default=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S"))
    what_happened = (
        f"Submitted a parent order for instrument {payload['instrumentId']} with quantity {payload['quantity']} "
        f"and urgency {payload['urgencyId']}. The engine returned parentOrderId {result.order.get('parentOrderId')}, "
        f"filled {filled_qty}, and left {remaining_qty} remaining."
    )

    display_header("Parent Order Submission Report", f"{result.inputs.base_url}/orders", str(completed_at))
    display(HTML(f"<div class='sor-report'>{badge(outcome, tone)}</div>"))
    display_kpis([
        ("Outcome", outcome),
        ("Parent order", result.order.get("parentOrderId", "")),
        ("Filled qty", filled_qty),
        ("Remaining qty", remaining_qty),
        ("Child orders", len(child_orders)),
    ])
    display_note(what_happened)
    display_table("1. Submission Manifest", result.manifest, "API endpoint and timing for this request.")
    display_table("2. Parent Order Payload", result.payload_frame, "Exact payload sent through SorClient.submit_parent_order.")
    display_table("3. Result List", result.result_list, "Plain-language checklist of the order result.")
    display_table("4. Submit Response", result.order_frame, "Response returned by POST /orders.")
    display_table("5. Order Status", result.status_frame, "Response returned by GET /orders/{parentOrderId}.")
    display_table("6. Child Orders", result.children_frame, "Venue-level child order evidence, when available.")


def display_failure_report(inputs: SubmitOrderInputs, exc: Exception) -> None:
    """Render a visible failure report when submission cannot complete."""

    failed_at = datetime.now(timezone.utc)
    manifest = pd.DataFrame([{
        "baseUrl": inputs.base_url,
        "failedAtUtc": failed_at.strftime("%Y-%m-%d %H:%M:%S"),
        "timeoutSeconds": inputs.timeout_seconds,
    }])
    display_styles()
    display_header("Parent Order Submission Report", f"{inputs.base_url}/orders", failed_at.strftime("%Y-%m-%d %H:%M:%S"))
    display(HTML(f"<div class='sor-report'>{badge('Submit failed', 'fail')}</div>"))
    display_note("Parent order submission failed: " + str(exc), tone="error")
    display_table("1. Submission Manifest", manifest, "API endpoint and timing for this request.")
    display_table("2. Parent Order Payload", pd.DataFrame([inputs.payload()]), "Payload prepared for SorClient.submit_parent_order.")


def display_styles() -> None:
    display(HTML(REPORT_CSS))


def display_header(title: str, subtitle: str, generated_at: str) -> None:
    display(HTML(f"""
    <div class="sor-report sor-hero">
      <h1>{escape(title)}</h1>
      <p>{escape(subtitle)}</p>
      <p>Generated at {escape(generated_at)} UTC</p>
    </div>
    """))


def display_section(title: str, subtitle: str = "") -> None:
    subtitle_html = f"<p>{escape(subtitle)}</p>" if subtitle else ""
    display(HTML(f"<div class='sor-report sor-section'><h2>{escape(title)}</h2>{subtitle_html}</div>"))


def display_note(text: str, *, tone: str = "note") -> None:
    css = "sor-error" if tone == "error" else ""
    display(HTML(f"<div class='sor-report sor-note {css}'>{escape(str(text))}</div>"))


def display_table(title: str, frame: pd.DataFrame | None, subtitle: str = "") -> None:
    display_section(title, subtitle)
    if frame is None or frame.empty:
        display_note("No rows were returned for this section.")
        return
    html = frame.to_html(index=False, escape=True).replace('class="dataframe"', 'class="sor-report-table"')
    display(HTML("<div class='sor-report'>" + html + "</div>"))


def display_kpis(cards: list[tuple[str, object]]) -> None:
    html = []
    for label, value in cards:
        html.append(
            "<div class='sor-kpi'>"
            f"<div class='sor-kpi-label'>{escape(str(label))}</div>"
            f"<div class='sor-kpi-value'>{escape(str(value))}</div>"
            "</div>"
        )
    display(HTML("<div class='sor-report sor-kpi-grid'>" + "".join(html) + "</div>"))


def badge(label: str, tone: str) -> str:
    css = {"pass": "sor-pass", "warn": "sor-warn", "fail": "sor-fail"}.get(tone, "sor-warn")
    return f"<span class='sor-badge {css}'>{escape(str(label))}</span>"


def first_value(frame: pd.DataFrame, *names: str, default: object = 0) -> object:
    for name in names:
        if frame is not None and name in frame.columns and len(frame) > 0:
            return frame.iloc[0][name]
    return default


def _load_widgets():
    try:
        import ipywidgets as widgets
    except ModuleNotFoundError:
        return None
    return widgets
