package com.nitroj.sor.sim.scenario;

/** Public parent-order request descriptor generated by simulator order injection. */
public record SimParentOrder(long parentOrderId, int instrumentId, int side, long quantity, int urgencyId,
                             long clientOrderRef, long arrivalEpochNanos) {
    public SimParentOrder {
        if (parentOrderId <= 0) {
            throw new IllegalArgumentException("parentOrderId must be positive");
        }
        if (instrumentId < 0) {
            throw new IllegalArgumentException("instrumentId must be non-negative");
        }
        if (quantity <= 0) {
            throw new IllegalArgumentException("quantity must be positive");
        }
        if (urgencyId < 0) {
            throw new IllegalArgumentException("urgencyId must be non-negative");
        }
    }
}
