package com.nitroj.sor.core.ml;

import java.io.IOException;
import java.io.Reader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Properties;

/**
 * Responsibility: read Phase 4 model artifact metadata.
 *
 * <p>Role in system: Java import validates model version, feature schema
 * compatibility, prediction file name, checksum, and row count before model
 * signals can be approved.</p>
 *
 * <p>Relationships: consumed by {@link ModelArtifactImporter} and
 * {@link ModelSignalValidator}.</p>
 *
 * <p>Lifecycle: loaded from {@code model_metadata.properties} generated by the
 * Python training job.</p>
 *
 * <p>Design intent: Java {@link Properties} keeps metadata parsing explicit and
 * dependency-free for the Adaptive Quantum SOR.</p>
 */
public record ModelArtifactMetadata(
        long modelVersion,
        String featureSchemaVersion,
        String predictionFile,
        String predictionChecksumSha256,
        int rowCount
) {
    public ModelArtifactMetadata {
        if (modelVersion <= 0) {
            throw new IllegalArgumentException("modelVersion must be positive");
        }
        if (featureSchemaVersion == null || featureSchemaVersion.isBlank()) {
            throw new IllegalArgumentException("featureSchemaVersion must not be blank");
        }
        if (predictionFile == null || predictionFile.isBlank()) {
            throw new IllegalArgumentException("predictionFile must not be blank");
        }
        if (predictionChecksumSha256 == null || predictionChecksumSha256.length() != 64) {
            throw new IllegalArgumentException("predictionChecksumSha256 must be a 64-character SHA-256 hex string");
        }
        if (rowCount <= 0) {
            throw new IllegalArgumentException("rowCount must be positive");
        }
    }

    public static ModelArtifactMetadata read(final Path metadataFile) throws IOException {
        if (metadataFile == null) {
            throw new IllegalArgumentException("metadataFile must not be null");
        }
        final Properties properties = new Properties();
        try (Reader reader = Files.newBufferedReader(metadataFile, StandardCharsets.UTF_8)) {
            properties.load(reader);
        }
        return new ModelArtifactMetadata(
                Long.parseLong(required(properties, "modelVersion")),
                required(properties, "featureSchemaVersion"),
                required(properties, "predictionFile"),
                required(properties, "predictionChecksumSha256"),
                Integer.parseInt(required(properties, "rowCount"))
        );
    }

    private static String required(final Properties properties, final String name) {
        final String value = properties.getProperty(name);
        if (value == null || value.isBlank()) {
            throw new IllegalArgumentException("metadata missing required field " + name);
        }
        return value.trim();
    }
}
