package com.nitroj.sor.api;

/**
 * Responsibility: sealed hierarchy of typed events emitted by the SOR engine.
 *
 * <p>Role in system: listeners receive these events asynchronously for route
 * decisions, child order emissions, fills, rejects, policy changes, session
 * changes, and backpressure.</p>
 *
 * <p>Relationships: consumed by {@link SorEventListener}; generated by
 * implementations of {@link SorEngine}.</p>
 *
 * <p>Lifecycle: event instances are created after routing or lifecycle changes
 * and delivered on the engine event-fanout thread.</p>
 *
 * <p>Design intent: a sealed interface gives integrators exhaustive switch
 * checking when handling the event stream.</p>
 */
public sealed interface SorEvent permits SorEvent.RouteDecided, SorEvent.ChildOrderEmitted,
        SorEvent.Filled, SorEvent.Rejected, SorEvent.PolicyPublished,
        SorEvent.SessionStatusChanged, SorEvent.BackpressureRejected {

    /**
     * Route decision event emitted once the engine determines child allocation.
     *
     * @param parentOrderId engine-assigned parent order identifier
     * @param policyVersion active policy version used for the decision
     * @param policyHash64 active policy hash used for the decision
     * @param childCount number of child orders emitted by the route
     * @param routedQuantity total quantity routed to child orders
     * @param residualQuantity parent quantity left unrouted
     * @param decidedEpochNanos wall-clock event timestamp in epoch nanoseconds
     */
    record RouteDecided(long parentOrderId, long policyVersion, long policyHash64,
                        int childCount, long routedQuantity, long residualQuantity,
                        long decidedEpochNanos) implements SorEvent {
    }

    /**
     * Child order emission event produced after a route decision writes a child.
     *
     * @param childOrderId engine-assigned child order identifier
     * @param parentOrderId engine-assigned parent order identifier
     * @param venueId destination venue identifier
     * @param side side encoded by {@link Side#BUY} or {@link Side#SELL}
     * @param quantity child order quantity
     * @param emittedEpochNanos wall-clock event timestamp in epoch nanoseconds
     */
    record ChildOrderEmitted(long childOrderId, long parentOrderId, int venueId,
                             int side, long quantity, long emittedEpochNanos) implements SorEvent {
    }

    /**
     * Fill event delivered from a venue or simulator callback.
     *
     * @param childOrderId engine-assigned child order identifier
     * @param parentOrderId engine-assigned parent order identifier
     * @param venueId venue reporting the fill
     * @param filledQuantity filled quantity
     * @param fillPrice fill price in fixed-point price units
     * @param filledEpochNanos wall-clock event timestamp in epoch nanoseconds
     */
    record Filled(long childOrderId, long parentOrderId, int venueId,
                  long filledQuantity, long fillPrice, long filledEpochNanos) implements SorEvent {
    }

    /**
     * Rejection event delivered when a child order cannot be accepted or filled.
     *
     * @param childOrderId engine-assigned child order identifier
     * @param parentOrderId engine-assigned parent order identifier
     * @param venueId venue reporting the rejection
     * @param reasonCode venue or engine rejection reason code
     * @param rejectedEpochNanos wall-clock event timestamp in epoch nanoseconds
     */
    record Rejected(long childOrderId, long parentOrderId, int venueId,
                    int reasonCode, long rejectedEpochNanos) implements SorEvent {
    }

    /**
     * Policy publication event emitted when a new policy becomes active.
     *
     * @param policyVersion active policy version after publication
     * @param policyHash64 active policy hash after publication
     * @param publishedEpochNanos wall-clock event timestamp in epoch nanoseconds
     */
    record PolicyPublished(long policyVersion, long policyHash64,
                           long publishedEpochNanos) implements SorEvent {
    }

    /**
     * Venue session state transition event.
     *
     * @param venueId venue whose status changed
     * @param oldStatus previous venue status
     * @param newStatus new venue status
     * @param changedEpochNanos wall-clock event timestamp in epoch nanoseconds
     */
    record SessionStatusChanged(int venueId, VenueStatus oldStatus,
                                VenueStatus newStatus, long changedEpochNanos) implements SorEvent {
    }

    /**
     * Backpressure event emitted when intake capacity rejects a parent order.
     *
     * @param parentOrderId rejected parent order identifier, if available
     * @param reasonCode engine backpressure reason code
     * @param rejectedEpochNanos wall-clock event timestamp in epoch nanoseconds
     */
    record BackpressureRejected(long parentOrderId, int reasonCode,
                                long rejectedEpochNanos) implements SorEvent {
    }
}
