package com.nitroj.sor.api;

/**
 * Responsibility: sealed hierarchy of typed events emitted by the SOR engine.
 *
 * <p>Role in system: listeners receive these events asynchronously for route
 * decisions, child order emissions, fills, rejects, policy changes, session
 * changes, and backpressure.</p>
 *
 * <p>Relationships: consumed by {@link SorEventListener}; generated by
 * implementations of {@link SorEngine}.</p>
 *
 * <p>Lifecycle: event instances are created after routing or lifecycle changes
 * and delivered on the engine event-fanout thread.</p>
 *
 * <p>Design intent: a sealed interface gives integrators exhaustive switch
 * checking when handling the event stream.</p>
 */
public sealed interface SorEvent permits SorEvent.RouteDecided, SorEvent.ChildOrderEmitted,
        SorEvent.Filled, SorEvent.Rejected, SorEvent.PolicyPublished,
        SorEvent.SessionStatusChanged, SorEvent.BackpressureRejected {

    /**
     * Route decision event emitted once the engine determines child allocation.
     */
    record RouteDecided(long parentOrderId, long policyVersion, long policyHash64,
                        int childCount, long routedQuantity, long residualQuantity,
                        long decidedEpochNanos) implements SorEvent {
    }

    /**
     * Child order emission event produced after a route decision writes a child.
     */
    record ChildOrderEmitted(long childOrderId, long parentOrderId, int venueId,
                             int side, long quantity, long emittedEpochNanos) implements SorEvent {
    }

    /**
     * Fill event delivered from a venue or simulator callback.
     */
    record Filled(long childOrderId, long parentOrderId, int venueId,
                  long filledQuantity, long fillPrice, long filledEpochNanos) implements SorEvent {
    }

    /**
     * Rejection event delivered when a child order cannot be accepted or filled.
     */
    record Rejected(long childOrderId, long parentOrderId, int venueId,
                    int reasonCode, long rejectedEpochNanos) implements SorEvent {
    }

    /**
     * Policy publication event emitted when a new policy becomes active.
     */
    record PolicyPublished(long policyVersion, long policyHash64,
                           long publishedEpochNanos) implements SorEvent {
    }

    /**
     * Venue session state transition event.
     */
    record SessionStatusChanged(int venueId, VenueStatus oldStatus,
                                VenueStatus newStatus, long changedEpochNanos) implements SorEvent {
    }

    /**
     * Backpressure event emitted when intake capacity rejects a parent order.
     */
    record BackpressureRejected(long parentOrderId, int reasonCode,
                                long rejectedEpochNanos) implements SorEvent {
    }
}
